### ISSUE TITLE
Document is compiled several times each time vim writes it

### ISSUE THREAD

**Issue by wichtounet** [GaretJax/pytex#5]
vim does not directly writes to the file, instead, it seems to write to a buffer then create/write/delete the file. 

The problem with that, is that, for each vim write, 4 events are launched: DELETE/CREATE/MODIFY/ATTRIB, meaning four compilations of the document. 

For now, I have commented the handling of all events but MODIFY and only one compilation is made. 

Do you know if there is a better solution to this problem ?

**Comment by GaretJax** [comment]
I don't like the solution proposed in #8 as it is not generic enough and introduces additional issues.

I printed the timestamped log and the three events all happen in less than < 0.1s. We can probably just wait for the tree to be stable before triggering a build. I wonder if we can do this easily enough without having to dig into (complicated) threading... 

Probably putting the pynotify observer in its own thread and notifying the main thread when the events queue is stable should work.

**Comment by wichtounet** [comment]
You're right, it would be better to merge the events together. I have seen that pyinotify has a coalesce_events function, but it doesn't seem to be enough for our problem. 

I implemented a simple coalesce function in #9. What do you think ?
It is probably not very good Python, but it works.

**Comment by GaretJax** [comment]
Did you try with the read_freq argument as well? (https://github.com/seb-m/pyinotify/blob/master/python2/examples/coalesce.py)

As long as it works the implementation does look good. There are some minor (mainly PEP8 related) issues, but I'll comment on them directly in the PR.

**Comment by wichtounet** [comment]
Yes, I tried that. I wasn't precise with the problem with the coalesce_events. The problem is that it only coalesces event with the exact same mask. In this case, we have IN_CREATED, IN_ATTRIB, IN_MODIFY at the same time, so coalesce_events does not work as we want.

**Comment by GaretJax** [comment]
Oh, ok. Thanks for clearing this up for me!

**Comment by GaretJax** [comment]
Fixed by #9
